### PR TITLE
Mavenize project

### PR DESCRIPTION
**Pull request by muff1nman**
Hi, I was looking to try this project out but as you only provide windows binaries, I was unable to test things out. I then looked to build from source, but found that it was quite unfriendly to do so due to the following problems:

- Not a maven based project
- File encodings of some files are quite strange (i.e. `./src/main/org/magic/api/providers/impl/ScryFallProvider.java` has some odd characters that don't show up on [github](https://github.com/nicho92/MtgDesktopCompanion/blob/2fe26e8fb989433e2024517ba5f8c4e48d00fef1/src/org/magic/api/providers/impl/ScryFallProvider.java#L549))
- Missing build instructions

Are you open to converting this into a maven project that is buildable on other systems other than windows? I started the effort and was able to get the project to start up but would probably need to coordinate to get this to a point where it could be merged.

### CODE REVIEW

**Comment by nicho92** [comment]
Really good idea to mavenize the project I'm really newbie in maven and collaboration in github (fork, branch,...).

i'll push pom.xml in the master repository

**Comment by muff1nman** [comment]
Okay awesome. I can help get you up to speed. Do you happen to have an irc channel to collaborate in more real time? Riot/Matrix is pretty handy too.

**Comment by muff1nman** [comment]
Here are the other things to do in my mind:

- Other files with encoding problems:

```
[ERROR] org/magic/game/actions/cards/MadnessActions.java:[39,40] error: unmappable character for encoding UTF8
[ERROR] org/magic/api/tokens/impl/CockatriceTokenProvider.java:[130,61] error: unmappable character for encoding UTF8
[ERROR] org/magic/api/tokens/impl/CockatriceTokenProvider.java:[182,61] error: unmappable character for encoding UTF8
[ERROR] org/magic/api/decksniffer/impl/LotusNoirDecks.java:[70,31] error: unmappable character for encoding UTF8
[ERROR] org/magic/gui/models/MagicCardTableModel.java:[15,99] error: unmappable character for encoding UTF8
[ERROR] org/magic/game/actions/cards/FlashbackActions.java:[39,40] error: unmappable character for encoding UTF8
[ERROR] org/magic/game/actions/cards/MorphActions.java:[42,40] error: unmappable character for encoding UTF8
```

- Finalize the dependencies 

There were a couple ones I was not sure about that I wanted to ask you about. Namely the substance, trident and laf ones. I couldn't find those exact dependencies in the maven central so I ended up using a fork of the original work at https://github.com/Insubstantial/insubstantial. Maybe that works, but if not we can reference the jars like is done for asciitable and mkm-api)

- Setup src and resources directory
 
According to maven standard convention (https://maven.apache.org/guides/introduction/introduction-to-the-standard-directory-layout.html), sources should be in a `src/main/java` directory and resources should be in a `src/main/resources` directory.

- Setup packaging.

I noticed you use some eclipse jar in jar thing to generate the final artifact, but I'm not sure how you generate the exe's. I think what we can do is use something similar like the maven shade plugin to build an "uber" jar (a jar with all dependencies included). That would be great for the developer type with java on their machine. Then we would need to find a good way to package this in an exe. Unfortunately that part is a bit out of my experience, but I think there are some plugins we could use that would do this for us (maybe https://github.com/lukaszlenart/launch4j-maven-plugin)

- Make sure git other file encodings are working correctly
When checking out the project, I have some issues with the `/templates` directory. Will need to look into this a bit more.

**Comment by nicho92** [comment]
> Other files with encoding problems:

OK, i'm looking for them.

>Finalize the dependencies

My bad for substantial L&F, my swing app doesn't respect standards of swing UI (using Swing Thread)... so i modifed substantial sourcecode to skip EDT's test.... it's horrible.. i know 👎 . Until i change all Thread calls in the app, I need to keep systemPath for this jar.

>Setup src and resources directory

done. thanks for help.

>Setup packaging.
i used install-4j, good tools (but commercial). It create setup packages for windows and unix(didn't tried yet). It will be nice to create a full setup with maven (don't know how yet). First version of this app was a big jar with all depedencies, but there was a big performance problem (especially with ImageIO....)

**Comment by muff1nman** [comment]
> OK, i'm looking for them.

The list I mentioned in my previous comment should make it so you don't have to look too far :)

> My bad for substantial L&F

Doesn't bother me - I just couldn't find some of the related jars on maven central. But yeah, we can change those ones to use the jars in the `/lib` directory.

> create a full setup with maven

I think this should get us started: http://sonatype.github.io/install4j-support/install4j-maven-plugin/usage.html

> big jar with all depedencies, but there was a big performance problem

Interesting, perhaps its due to access the resources wrapped up in the jar directly with the zip overhead? I imagine it shouldn't be too hard to setup a resource cache on the users file system.

Let me know if I can help with anything. I think its best if you address some of the file encoding things first as I don't have the original files.

**Pull request closed without merging**
